spring:
  application:
    name: tg-bot-personal-assistant

  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

telegram:
  bot:
    token: ${TG_TOKEN}
    name: ${TG_BOT_NAME}

translation:
  google:
    api-key: ${GOOGLE_API_KEY}

weather:
  open-weather-map:
    token: ${OPEN_WEATHER_MAP_TOKEN}

org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true